### ISSUE TITLE
typing_extensions as missing dependency in python 3.8 and python 3.9

### ISSUE THREAD

**Issue by chrisdecker1201** [akaihola/darker#202]
Hello,

yesterday I started using darker in my environment and discovered an issue that typing_extensions is missing when I'm using python 3.8/3.9

~~~
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/timeslime-server-_mR8Jzc2/bin/darker", line 5, in <module>
    from darker.__main__ import main_with_error_handling
  File "/root/.local/share/virtualenvs/timeslime-server-_mR8Jzc2/lib/python3.8/site-packages/darker/__main__.py", line 11, in <module>
    from darker.black_diff import (
  File "/root/.local/share/virtualenvs/timeslime-server-_mR8Jzc2/lib/python3.8/site-packages/darker/black_diff.py", line 42, in <module>
    from black import FileMode as Mode
  File "/root/.local/share/virtualenvs/timeslime-server-_mR8Jzc2/lib/python3.8/site-packages/black/__init__.py", line 48, in <module>
    from black.files import find_project_root, find_pyproject_toml, parse_pyproject_toml
  File "/root/.local/share/virtualenvs/timeslime-server-_mR8Jzc2/lib/python3.8/site-packages/black/files.py", line 26, in <module>
    from black.handle_ipynb_magics import jupyter_dependencies_are_installed
  File "/root/.local/share/virtualenvs/timeslime-server-_mR8Jzc2/lib/python3.8/site-packages/black/handle_ipynb_magics.py", line 15, in <module>
    from typing_extensions import TypeGuard
ModuleNotFoundError: No module named 'typing_extensions'
~~~

## Steps to reproduce
~~~bash
pip install pipenv black darker mypy
pipenv --python 3.8 install -d
pipenv run darker --check --revision origin/$CI_DEFAULT_BRANCH -i -L mypy .
~~~

## Probably the solution

change settings in `setup.cfg`
~~~
install_requires =
    black>=21.5b1
    toml
    typing-extensions ; python_version < "3.8"
~~~

**Comment by akaihola** [comment]
Hi @chrisdecker1201, thanks for the report!

Unfortunately for some reason I can't reproduce this on my laptop.

I'm also wondering - if `typing_extensions` is a required dependency for Black, why doesn't it get installed? What if you leave Darker out from your environment and try just running Black, do you still get the same error?

Can you repeat the same symptom using just `pip` and a virtualenv, without using `pipenv`? Could this be a bug in `pipenv`?

**Comment by akaihola** [comment]
Also, if I create a new virtualenv with Python 3.8 or Python 3.9, and install Darker in it, `typing_extensions` does get installed, even though Darker itself only requires it when using Python 3.7 and below. Black seems to always require it.
```bash
$ python3.8 -m venv myvenv
$ source myvenv/bin/activate
$ pip install darker
Collecting darker
  Using cached darker-1.3.0-py3-none-any.whl (67 kB)
Collecting black>=21.5b1
  Using cached black-21.9b0-py3-none-any.whl (148 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting pathspec<1,>=0.9.0
  Using cached pathspec-0.9.0-py2.py3-none-any.whl (31 kB)
Collecting regex>=2020.1.8
  Using cached regex-2021.8.28-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (761 kB)
Collecting tomli<2.0.0,>=0.2.6
  Using cached tomli-1.2.1-py3-none-any.whl (11 kB)
Collecting mypy-extensions>=0.4.3
  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting typing-extensions>=3.10.0.0
  Using cached typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Collecting click>=7.1.2
  Using cached click-8.0.1-py3-none-any.whl (97 kB)
Collecting platformdirs>=2
  Using cached platformdirs-2.3.0-py3-none-any.whl (13 kB)
Installing collected packages: pathspec, regex, tomli, mypy-extensions, typing-extensions, click, platformdirs,
                               black, toml, darker
Successfully installed black-21.9b0 click-8.0.1 darker-1.3.0 mypy-extensions-0.4.3 pathspec-0.9.0
                       platformdirs-2.3.0 regex-2021.8.28 toml-0.10.2 tomli-1.2.1 typing-extensions-3.10.0.2
```

**Comment by chrisdecker1201** [comment]
I could not reproduce my issue locally or inside a docker container. It's only on my builds running inside a GitLab Runner.

e.g. https://gitlab.com/lookslikematrix/timeslime-server/-/jobs/1611159883

**Comment by akaihola** [comment]
I _can_ reproduce it using:
```bash
podman run -it python:3.8 bash
git clone https://gitlab.com/lookslikematrix/timeslime-server.git
pip install pipenv
pipenv --python 3.8 install -d
pipenv run darker --check --revision origin/master -i -L mypy .
```
This outputs:
```python
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/timeslime-server-4zk2Rnv2/bin/darker", line 5, in <module>
    from darker.__main__ import main_with_error_handling
  File "/root/.local/share/virtualenvs/timeslime-server-4zk2Rnv2/lib/python3.8/site-packages/darker/__main__.py", line 11, in <module>
    from darker.black_diff import (
  File "/root/.local/share/virtualenvs/timeslime-server-4zk2Rnv2/lib/python3.8/site-packages/darker/black_diff.py", line 42, in <module>
    from black import FileMode as Mode
  File "/root/.local/share/virtualenvs/timeslime-server-4zk2Rnv2/lib/python3.8/site-packages/black/__init__.py", line 48, in <module>
    from black.files import find_project_root, find_pyproject_toml, parse_pyproject_toml
  File "/root/.local/share/virtualenvs/timeslime-server-4zk2Rnv2/lib/python3.8/site-packages/black/files.py", line 26, in <module>
    from black.handle_ipynb_magics import jupyter_dependencies_are_installed
  File "/root/.local/share/virtualenvs/timeslime-server-4zk2Rnv2/lib/python3.8/site-packages/black/handle_ipynb_magics.py", line 15, in <module>
    from typing_extensions import TypeGuard
ModuleNotFoundError: No module named 'typing_extensions'
```
And indeed this command:
```bash
/root/.local/share/virtualenvs/timeslime-server-4zk2Rnv2/bin/pip list
```
outputs this which does not contain `typing_extensions`:
```
Package           Version
----------------- ---------
astroid           2.6.6
attrs             21.2.0
black             21.9b0
click             8.0.1
coverage          6.0b1
darker            1.3.0
Flask             2.0.1
iniconfig         1.1.1
isort             5.9.3
itsdangerous      2.0.1
Jinja2            3.0.1
lazy-object-proxy 1.6.0
MarkupSafe        2.0.1
mccabe            0.6.1
mypy              0.910
mypy-extensions   0.4.3
packaging         21.0
pathspec          0.9.0
pip               21.2.4
platformdirs      2.3.0
pluggy            1.0.0
py                1.10.0
pylint            3.0.0a4
pyparsing         3.0.0rc1
pytest            6.2.5
pytest-cov        2.12.1
regex             2021.8.28
setuptools        58.0.4
toml              0.10.2
tomli             1.2.1
waitress          2.0.0
Werkzeug          2.0.1
wheel             0.37.0
wrapt             1.12.1
```

**Comment by akaihola** [comment]
Here in [pipenv-install-output.log](https://github.com/akaihola/darker/files/7223095/pipenv-install-output.log) is the complete verbose output from
```bash
pipenv -v --python 3.8 install -d
```
Analyzing that will probably clarify why it fails to include `typing_extensions` in installed packages.

**Comment by akaihola** [comment]
And here in [pipenv-install-no-lock.log](https://github.com/akaihola/darker/files/7223122/pipenv-install-no-lock.log) is the output from running the same but with only `Pipfile` in a fresh directory, so we see the whole dependency resolution and locking process.

In this case, `typing-extensions` _is_ included!

**Comment by akaihola** [comment]
@chrisdecker1201, I would recommend looking at [pypa/pipenv open issues](https://github.com/pypa/pipenv/issues/) to see whether this is already being addressed, and if not, submitting an issue and referring to this conversation.

If you end up filing a new bug, it would probably be good to try and
- trim down `Pipfile` to the absolute minimum which still reproduces this, and
- see what is the essential difference between a sole `Pipfile` and a full `timeslime-server` checkout which then triggers this behavior

**Comment by akaihola** [comment]
@chrisdecker1201, I analyzed the diff between two log files (ignoring hashes and different sorting), and the first significant difference is here (with added line breaks for clarity):
```diff
1245c1
< Writing supplied requirement line to temporary file: "typing-extensions==3.10.0.2; python_version < '3.8'
--hash=sha256:49f75d16ff11f1cd258e1b988ccff82a3ca5570217d7ad8c5f48205dd99a677e
--hash=sha256:f1d25edafde516b146ecd0613dabcc61409817af4766fbbcfb8d1ad4ec441a34
--hash=sha256:d8226d10bc02a29bcc81df19a26e56a9647f8b0a6d4a83924139f4a8b01f17b7"
---
> Writing supplied requirement line to temporary file: 'typing-extensions==3.10.0.2
--hash=sha256:49f75d16ff11f1cd258e1b988ccff82a3ca5570217d7ad8c5f48205dd99a677e
--hash=sha256:f1d25edafde516b146ecd0613dabcc61409817af4766fbbcfb8d1ad4ec441a34
--hash=sha256:d8226d10bc02a29bcc81df19a26e56a9647f8b0a6d4a83924139f4a8b01f17b7'
```

**Comment by chrisdecker1201** [comment]
@akaihola Thank you so much :). I'm astonished how much effort you put into my issue.

I found the following difference:

* without lock `typing_extensions` is getting installed
~~~
Collecting typing-extensions==3.10.0.2
  Using cached typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Installing collected packages: typing-extensions
Successfully installed typing-extensions-3.10.0.2
~~~
* with lock `typing_extensions` is getting **not** installed
~~~
Ignoring typing-extensions: markers 'python_version < "3.8"' don't match your environment
~~~

**Comment by chrisdecker1201** [comment]
So is it really not required on python versions higher than 3.7?

**Comment by akaihola** [comment]
Darker itself doesn't require it on Python3.8+ since it only uses extensions which are included in Python 3.8.

But it seems Black recently started to use some newer extensions not yet in Python 3.8 and 3.9, so running Darker _effectively_ does require `typing-extensions` in all current Python versions.

From a purist point of view, I think Darker's `setup.cfg` is still correct. For example, if we do modify it to require `typing-extensions` unconditionally, and then for some reason Black's next release doesn't need it any more, that will result in it being installed unnecessarily.

Dependency management in Python tooling, be it `pip` or `pipenv` or `poetry`, should manage this correctly. And if they don't I consider it a bug.

**Comment by chrisdecker1201** [comment]
In this case, you're correct. I'll maybe dig deeper for this issue, but then it's really a pipenv issue.

**Comment by chrisdecker1201** [comment]
For now I'm just using `--skip-lock`
