### ISSUE TITLE
Incorrect paths with --stdout option

### ISSUE THREAD

**Issue by levouh** [akaihola/darker#228]
```
┏ fedora · master · ~/tmp/python 
┗ pwd
/home/amasquelier/tmp/python
┏ fedora · master · ~/tmp/python 
┗ readlink -f ./src/menu.py 
/home/amasquelier/tmp/python/src/menu.py
┏ fedora · master · ~/tmp/python 
┗ darker -i --stdout ./src/menu.py
Traceback (most recent call last):
  File "/home/amasquelier/.local/bin/darker", line 8, in <module>
    sys.exit(main_with_error_handling())
  File "/home/amasquelier/.local/lib/python3.9/site-packages/darker/__main__.py", line 383, in main_with_error_handling
    return main()
  File "/home/amasquelier/.local/lib/python3.9/site-packages/darker/__main__.py", line 360, in main
    for path, old, new in format_edited_parts(
  File "/home/amasquelier/.local/lib/python3.9/site-packages/darker/__main__.py", line 69, in format_edited_parts
    rev2_content = git_get_content_at_revision(
  File "/home/amasquelier/.local/lib/python3.9/site-packages/darker/git.py", line 63, in git_get_content_at_revision
    return TextDocument.from_file(abspath)
  File "/home/amasquelier/.local/lib/python3.9/site-packages/darker/utils.py", line 116, in from_file
    mtime = datetime.utcfromtimestamp(path.stat().st_mtime).strftime(GIT_DATEFORMAT)
  File "/usr/lib64/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
FileNotFoundError: [Errno 2] No such file or directory: '/home/amasquelier/tmp/python/src/src/menu.py'
┏ fedora · master · ~/tmp/python 
┗ darker --version
1.3.1
```

Note that this works fine with `--diff`, or no arguments (except `-i` and the path to the file) so it appears to be an issue with `--stdout`.

**Comment by levouh** [comment]
Debugging a bit, this is actually just a byproduct of `pathlib.Path`, same thing happens with `os.path.join`.
