### ISSUE TITLE
`EOF in multi-line statement`for a fresh Pylint configuration

### ISSUE THREAD

**Issue by akaihola** [akaihola/darker#375]
Hey, i encountered another thing.
I tried upgrading to Python 3.10 but now i get a new error, which comes when using pylints config file option.
The file is freshly generated with `pylint --generate-rcfile > pylint.conf`
```
lint = [ "pylint --rcfile=tools/pylint.conf" ]
```

```
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to ...\.cache\pre-commit\patch1660718692-12008.
darker...................................................................Failed
- hook id: darker
- exit code: 1
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\darker.EXE\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\darker\__main__.py", line 487, in main_with_error_handling
    return main()
  File "C:\Python310\lib\site-packages\darker\__main__.py", line 469, in main
    linter_failures_on_modified_lines = run_linters(
  File "C:\Python310\lib\site-packages\darker\linting.py", line 173, in run_linters
    return sum(
  File "C:\Python310\lib\site-packages\darker\linting.py", line 174, in <genexpr>
    run_linter(linter_cmdline, root, paths, revrange, use_color)
  File "C:\Python310\lib\site-packages\darker\linting.py", line 133, in run_linter
    edited_linenums = edited_linenums_differ.compare_revisions(
  File "C:\Python310\lib\site-packages\darker\git.py", line 460, in compare_revisions
    return _compare_revisions(
  File "C:\Python310\lib\site-packages\darker\git.py", line 429, in _compare_revisions
    linenums = _revision_vs_lines(root, path_in_repo, rev1, content, context_lines)
  File "C:\Python310\lib\site-packages\darker\git.py", line 402, in _revision_vs_lines
    multiline_string_ranges = get_multiline_string_ranges(content)
  File "C:\Python310\lib\site-packages\darker\multiline_strings.py", line 20, in get_multiline_string_ranges
    return [
  File "C:\Python310\lib\site-packages\darker\multiline_strings.py", line 20, in <listcomp>
    return [
  File "C:\Python310\lib\tokenize.py", line 523, in _tokenize
    raise TokenError("EOF in multi-line statement", (lnum, 0))
tokenize.TokenError: ('EOF in multi-line statement', (283, 0))
[INFO] Restored changes from ...\.cache\pre-commit\patch1660718692-12008.
```

_Originally posted by @deadkex in https://github.com/akaihola/darker/discussions/368#discussioncomment-3412611_

**Comment by akaihola** [comment]
What does `pylint.conf` look like? Maybe a final newline is missing?

Could you double check whether this was due to the Python update or due to a Pylint update?

**Comment by deadkex** [comment]
On my personal pc, the error doesn't appear when using a fresh config file. Maybe the new pylint update fixed something. Will test next week on the work pc.

**Comment by akaihola** [comment]
Hi @deadkex, do you recall drawing any conclusions on this?

**Comment by deadkex** [comment]
> Hi @deadkex, do you recall drawing any conclusions on this?

Hey, i don't remember what i did about this but i think i somehow managed to work around it, sorry.
