### ISSUE TITLE
Use exit code 21 in GitHub action if `working-directory` is missing

### ISSUE THREAD

**Issue by akaihola** [akaihola/darker#594]
For error handling, it would be useful to have a unique exit code from the Darker GitHub action if the directory specified as `working-directory` doesn't exist.

Here's the current behavior:
```python
Traceback (most recent call last):
  File "/home/runner/work/darker/darker/action/main.py", line 59, in <module>
    proc = run(  # nosec
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/_temp/non-existent-dir'
##[error]Process completed with exit code 1.
```

Darker itself uses an exit code of `2` if a file doesn't exist. For example 21 as a variation of that code could be used for the action.

**Comment by reneleonhardt** [comment]
Actually, the action used the exit code `1` 😅
`Errno 2` is only an internal error code, you can see it in many python programs if they print stack traces.

I don't really follow, why would different exit codes matter to consumers of the GitHub Action?

Much better would be not to print stack traces for expected errors like FileNotFoundError, but meaningful error messags like
```
working-directory: abc not found, please check your configuration.
```

And a corresponding README section would be helpful, explaining all inputs in a minimal way.
The usage example doesn't even mention `working-dir` for example.
https://github.com/akaihola/darker#usage

**Comment by akaihola** [comment]
Thanks @reneleonhardt for your feedback!

This change has actually already been made last January in #591...

>Actually, the action used the exit code 1 😅

You mean when the working directory is missing? Are you sure?

>`Errno 2` is only an internal error code, you can see it in many python programs if they print stack traces.

I guess what I mentioned in `Darker itself uses an exit code of 2 if a file doesn't exist` demonstrates this exact behavior:
```python
$ darker /tmp/foo
ERROR:darker.__main__:Path(s) '/tmp/foo' do not exist in the working tree (2)
Traceback (most recent call last):
  File "darker/__main__.py", line 637, in main_with_error_handling
    return main()
           ^^^^^^
  File "darker/__main__.py", line 561, in main
    raise FileNotFoundError(msg)
FileNotFoundError: Path(s) '/tmp/foo' do not exist in the working tree
$ echo $?
2
```

>I don't really follow, why would different exit codes matter to consumers of the GitHub Action?

I've been really sloppy when writing the description for this issue: I can't remember exactly what I was thinking back in the day. My best guess is that it was impossible to write test for the GitHub action for the missing working directory case. However, it seems there is no such test, so either that wasn't the reason, or I forgot to actually create that test.

>Much better would be not to print stack traces for expected errors like FileNotFoundError, but meaningful error messags like
>```
>working-directory: abc not found, please check your configuration.
>```

You're right. I'll create a separate issue for that. Different error codes could still be returned if that is seen necessary.

>And a corresponding README section would be helpful, explaining all inputs in a minimal way.
>The usage example doesn't even mention `working-dir` for example.

So a comprehensive README section for the GitHub action? I'll make another separate issue for that one as well.

I'm closing this one in favor of the follow-up issues mentioned above.
